services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: risk
      POSTGRES_PASSWORD: risk
      POSTGRES_DB: riskdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: riskdb

volumes:
  pgdata:
